package com.card.service.card;

import com.card.service.card.entities.Card;
import com.card.service.card.repositories.CardRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class CardApplication implements CommandLineRunner
{

	@Autowired
	CardRepository cardRepository;

	public static void main(String[] args) {
		SpringApplication.run(CardApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		Card lamball = new Card(1, "Lamball", "A walk up a hill tends to end with this Pal tumbling back down. This causes it to become dizzy and unable to move, making it easy to capture and kill. As a result, this pal has tumbled down to the very bottom of the food chain itself.", "neutral", "humanoid", 70, 70, 0, 1, "https://static.wikia.nocookie.net/palworld/images/0/01/Lamball_menu.png/");
		Card cattiva = new Card(2, "Cattiva", "At a glance it appears full of confidence, but it is in fact weak and cowardly. Being toyed with by a Cattiva is in many ways the greatest of disgraces.", "neutral", "humanoid", 70, 70, 5, 1, "https://static.wikia.nocookie.net/palworld/images/5/51/Cattiva_menu.png/");
		Card chikipi = new Card(3, "Chikipi", "Extremely weak and far too delicious. It is one of the weakest Pal alongside Lamball. No matter how many are hunted, they just keep appearing.", "neutral", "bird", 65, 60, 5, 1, "https://static.wikia.nocookie.net/palworld/images/f/f4/Chikipi_menu.png/");
		Card lifmunk = new Card(4, "Lifmunk", "Intelligent as a five to sever-year-old human child. It makes a wonderful partner, but there have been more than a few cases where they've killed their master after learning to use weapons.", "grass", "humanoid", 70, 75, 10, 1, "https://static.wikia.nocookie.net/palworld/images/d/dc/Lifmunk_menu.png/");
		Card foxparks = new Card(5, "Foxparks", "It is unskilled at controlling fire from the moment it is born and tends to choke on the flames it breathes unintentionally. Foxparks sneezes are one of the leading causes of forest fires.", "fire", "fourlegged", 72, 65, 40, 1, "https://static.wikia.nocookie.net/palworld/images/d/d7/Foxparks_menu.png/");
		Card fuack = new Card(6, "Fuack", "Using its own body water, this Pal can create waves anywhere. It body surfs when in a hurry, but the resulting speed often ends in a fatal collision.", "water", "humanoid", 80, 60, 120, 1, "https://static.wikia.nocookie.net/palworld/images/5/5e/Fuack_menu.png/");
		Card sparkit = new Card(7, "Sparkit", "During the dry season, this Pal is always on the verge of blowing a fuse, Sparks can fly with even the slightest provocation even amongst allies.", "electric", "humanoid", 67, 60, 30, 1, "https://static.wikia.nocookie.net/palworld/images/c/ce/Sparkit_menu.png/");
		Card tanzee = new Card(8, "Tanzee", "Long ago, this Pal used long objects like tree branches as weapons. After coming into contact with humans, however, it found something much more effective: guns.", "grass", "humanoid", 85, 80, 280, 1, "https://static.wikia.nocookie.net/palworld/images/4/40/Tanzee_menu.png/");
		Card rooby = new Card(9, "Rooby", "Wild Rooby surprisingly never get sick. Eating one piece of charcoal a day, made by burning a branch, is the secret to its eternal health.", "fire", "fourlegged", 85, 75, 1950, 2, "https://static.wikia.nocookie.net/palworld/images/2/21/Rooby_menu.png/");
		Card pengullet = new Card(10, "Pengullet", "The feathers of this Pal have all but disappeared, but sadly, its desire to fly has remained as strong as ever. Even now, it tries to fly again in any way it can.", "water", "humanoid", 72, 70, 80, 1, "https://static.wikia.nocookie.net/palworld/images/3/38/Pengullet_menu.png/");
		Card penking = new Card(11, "Penking", "Surprisingly, it is unrelated to Pengullet. Ever wanting to be the center of attention, this Pal will strut its stuff for any onlookers.", "water", "humanoid", 82, 95, 4410, 6, "https://static.wikia.nocookie.net/palworld/images/b/b5/Penking_menu.png/");
		Card jolthog = new Card(12, "Jolthog", "Releases the electricity stored in it's body when under attack, producing a shock that can be over 10 million volts. If thrown, it can even be more lethal than any conventional heavy weaponry.", "electric", "fourlegged", 72, 70, 60, 1, "https://static.wikia.nocookie.net/palworld/images/5/52/Jolthog_menu.png/");
		Card gumoss = new Card(13, "Gumoss", "A strange Pal with a body resembling tree sap. It gradually loses strength if it has nothing to cover its body with, eventually rotting away.", "grass", "other", 85, 70, 310, 1, "https://static.wikia.nocookie.net/palworld/images/2/2e/Gumoss_menu.png/");
		Card vixy = new Card(14, "Vixy", "The idol of Palpagos Island. If you bully a Vixy, you best be prepared to become enemies with the whole world.", "neutral", "fourlegged", 70, 70, 0, 2, "https://static.wikia.nocookie.net/palworld/images/9/9e/Vixy_menu.png/");
		Card hoocrates = new Card(15, "Hoocrates", "Often lost in thought, it sometimes finds it difficult to sleep. \"I think, therefore I am.\"", "dark", "bird", 70, 70, 50, 1, "https://static.wikia.nocookie.net/palworld/images/e/ef/Hoocrates_menu.png/");
		Card teafant = new Card(16, "Teafant", "Large amounts of water pour from what is thought to be its nose, though some say that it is, in fact, just snot. This has sparked a fierce debate among Pal scholars.", "water", "fourlegged", 65, 70, 5, 1, "https://static.wikia.nocookie.net/palworld/images/a/a7/Teafant_menu.png/");
		Card depresso = new Card(17, "Depresso", "It has few friends because of the perpetually grouchy look on its face, but it is in fact kindhearted. Some have seen it feeding Vixy who have strayed from their pack.", "dark", "humanoid", 70, 70, 50, 1, "https://static.wikia.nocookie.net/palworld/images/d/d9/Depresso_menu.png/");
		Card cremis = new Card(18, "Cremis", "Compared to Lamball, it has finer wool and a temperament more suited for domestication. However, it has historically been kept as a pet. Cuteness is considered a virtue.", "neutral", "fourlegged", 85, 70, 420, 1, "https://static.wikia.nocookie.net/palworld/images/a/a1/Cremis_menu.png/");
		Card daedream = new Card(19, "Daedream", "It puts those it is interested in to sleep and shows them an endless stream of happy dreams. Those who fall under its spell are never to wake until death takes them.", "dark", "humanoid", 87, 70, 330, 1, "https://static.wikia.nocookie.net/palworld/images/e/e6/Daedream_menu.png/");
		Card rushoar = new Card(20, "Rushoar", "Being extremely aggressive Pal, it often picks fights before gauging its opponent's strength. Though small, its powerful charge can even send boulders flying.", "ground", "fourlegged", 85, 80, 680, 1, "https://static.wikia.nocookie.net/palworld/images/d/d0/Rushoar_menu.png/");
		Card nox = new Card(21, "Nox", "If you find Nox hair in your bedding, you should leave it where it lays and leave immediately. Picking it up is a one-way-ticket to a never ending night.", "dark", "fourlegged", 77, 75, 480, 6, "https://static.wikia.nocookie.net/palworld/images/5/55/Nox_menu.png/");
		Card fuddler = new Card(22, "Fuddler", "Its large claws boast of diamond-like hardness. However, sharpening these claws consumes most of its energy, leading it to sometimes spending entire days doing nothing else.", "ground", "humanoid", 90, 65, 360, 1, "https://static.wikia.nocookie.net/palworld/images/6/64/Fuddler_menu.png/");
		Card killamari = new Card(23, "Killamari", "It wraps itself around an enemy's head, sucking out their insides. Pal mummies are occasionally found, but these are in fact Killamari victims.", "dark", "other", 80, 60, 200, 1, "https://static.wikia.nocookie.net/palworld/images/8/80/Killamari_menu.png/");
		Card mau = new Card(24, "Mau", "Its hard tail does not deteriorate even when cut off. Some believed these severed tails to be good luck, but for the innumerable Mau who were poached as a result, they were anything but.", "dark", "fourlegged", 65, 70, 5, 1, "https://static.wikia.nocookie.net/palworld/images/1/17/Mau_menu.png/");
		Card celaray = new Card(25, "Celaray", "Riding the wind, this Pal travels where it pleases. Should it find a partner along the way, the encounter will mark its journey's end.", "water", "other", 85, 80, 1860, 3, "https://static.wikia.nocookie.net/palworld/images/9/95/Celaray_menu.png/");
		Card direhowl = new Card(26, "Direhowl", "Long ago Direhowl would hunt alongside humans but over the years this bond faded.", "neutral", "fourlegged", 100, 80, 920, 2, "https://static.wikia.nocookie.net/palworld/images/1/19/Direhowl_menu.png/");
		Card tocotoco = new Card(27, "Tocotoco", "A frightening Pal that produces exploding eggs. It often fires these eggs from its rear end as a weapon, but when spent the Pal itself explodes.", "neutral", "bird", 77, 60, 90, 1, "https://static.wikia.nocookie.net/palworld/images/5/5b/Tocotoco_menu.png/");
		Card flopie = new Card(28, "Flopie", "It prefers places that have an abundance of vegetation, but hay fever has apparently become a problem for Flopie as of late.", "grass", "humanoid", 82, 75, 220, 1, "https://static.wikia.nocookie.net/palworld/images/5/5e/Flopie_menu.png/");
		Card mozzarina = new Card(29, "Mozzarina", "Milk pours from this Pal like water from an open faucet, regardless of its gender. It's truly a mystery of life, although this mystery may be better left unsolved.", "neutral", "fourlegged", 75, 90, 1620, 2, "https://static.wikia.nocookie.net/palworld/images/3/3a/Mozzarina_menu.png/");
		Card bristla = new Card(30, "Bristla", "This prickly Pal's thorns are highly poisonous. It is friendly with Cinnamoth and only smiles when Cinnamoth is drinking its nectar.", "grass", "humanoid", 80, 80, 140, 1, "https://static.wikia.nocookie.net/palworld/images/1/13/Bristla_menu.png/");
		Card gobfin = new Card(31, "Gobfin", "Long ago, it was a large and powerful aquatic Pal. As food became scarce it evolved to live on land. Since walking requires much energy, it gradually became smaller and is now a small and puny Pal.", "water", "humanoid", 90, 90, 840, 2, "https://static.wikia.nocookie.net/palworld/images/f/ff/Gobfin_menu.png/");
		Card hangyu = new Card(32, "Hangyu", "Its gigantic arms can rip apart even iron. As a particularly cruel form of execution, serious criminals would be strung up in a public square, and a Hangyu would rip off the skin from their bones.", "ground", "other", 70, 80, 20, 1, "https://static.wikia.nocookie.net/palworld/images/0/08/Hangyu_menu.png/");
		Card mossanda = new Card(33, "Mossanda", "A Pal so powerful it's hard to believe. In one experiment, this Pal tore through 3,000 sheets of paper at once! It's only by some miracle that this Pal isn't a meat-eater.", "grass", "humanoid", 95, 100, 5200, 6, "https://static.wikia.nocookie.net/palworld/images/d/db/Mossanda_menu.png/");
		Card woolipop = new Card(34, "Woolipop", "Its entire body is 18,000 times sweeter than sugar. Carnivorous Pals lured by its scent will find themselves overwhelmed by sweetness and even pass out should they take a bite of this Pal.", "neutral", "fourlegged", 70, 70, 450, 3, "https://static.wikia.nocookie.net/palworld/images/f/fa/Woolipop_menu.png/");
		Card caprity = new Card(35, "Caprity", "The shrub on this pal's back produces berries as long as it is properly fed. It offers these berries to potential mates, and if the flavor is to their liking, romance blossoms.", "grass", "fourlegged", 70, 100, 1510, 3, "https://static.wikia.nocookie.net/palworld/images/a/a7/Caprity_menu.png/");
		Card melpaca = new Card(36, "Melpaca", "Don't be fooled by its fluffy appearance. A hypersonic kick from one of its long legs may send you flying to the other side of the world.", "neutral", "fourlegged", 82, 90, 1740, 3, "https://static.wikia.nocookie.net/palworld/images/7/7f/Melpaca_menu.png/");
		Card eikthyrdeer = new Card(37, "Eikthyrdeer", "The one who possesses the most impressive antlers becomes the leader of the herd. If their antlers are broken, they become depressed and leave the herd never to be seen again.", "neutral", "fourlegged", 75, 95, 1620, 4, "https://static.wikia.nocookie.net/palworld/images/4/40/Eikthyrdeer_menu.png/");
		Card nitewing = new Card(38, "Nitewing", "It carries newborn Pals to its nest and raises them as a surrogate parent.  Once the baby Pal has fattened up, it hunts them.", "neutral", "bird", 97, 100, 5300, 3, "https://static.wikia.nocookie.net/palworld/images/3/34/Nitewing_menu.png/");
		Card ribbuny = new Card(39, "Ribbuny", "A Pal who's never without a bright smile. Occasionally, it gets its tentacles tied up in knots by Cattiva's pranks. During those moments, its expression changes into something altogether demonic.", "neutral", "humanoid", 82, 75, 160, 1, "https://static.wikia.nocookie.net/palworld/images/7/7e/Ribbuny_menu.png/");
		Card incineram = new Card(40, "Incineram", "In the dark of night, this Pal snatches prey to bring back ot its territory. What happens to those poor souls afterwards isn't too hard to imagine.", "fire", "humanoid", 125, 95, 3780, 4, "https://static.wikia.nocookie.net/palworld/images/4/40/Incineram_menu.png/");
		Card cinnamoth = new Card(41, "Cinnamoth", "Sniffing its scales produces a feeling of unparalleled euphoria. There was some effort to further regulate this byproduct, but the Free Pal Alliance have vehemently opposed these measures, putting a stop to them.", "grass", "bird", 90, 70, 4700, 4, "https://static.wikia.nocookie.net/palworld/images/7/7e/Cinnamoth_menu.png/");
		Card arsox = new Card(42, "Arsox", "In ancient times, carnivorous Pals pursued them relentlessly. The Arsox's irrational rage transformed into a raging inferno, which has been passed on to this day.", "fire", "fourlegged", 97, 85, 2520, 4, "https://static.wikia.nocookie.net/palworld/images/f/f5/Arsox_menu.png/");
		Card dumud = new Card(43, "Dumud", "When too relaxed, its reaction time drastically declines. Even if it were sliced from head to tail, it probably wouldn't even realize that it should be dead until the next morning.", "ground", "fish", 85, 100, 3690, 4, "https://static.wikia.nocookie.net/palworld/images/3/32/Dumud_menu.png/");
		Card cawgnito = new Card(44, "Cawgnito", "Long ago it freely soared the skies. After losing a contest with Galeclaw, it abandoned the skies and now lives a quiet nocturnal life.", "dark", "bird", 87, 75, 840, 3, "https://static.wikia.nocookie.net/palworld/images/f/f6/Cawgnito_menu.png/");
		Card leezpunk = new Card(45, "Leezpunk", "A Pal that always takes great care to maintain a stylish stance. Always on the hunt for the coolest poses, if given a mirror it will spend all day posing in front of it.", "dark", "humanoid", 85, 80, 720, 2, "https://static.wikia.nocookie.net/palworld/images/0/09/Leezpunk_menu.png/");
		Card loupmoon = new Card(46, "Loupmoon", "The horns on its head grow under the moonlight. It doesn't hate the sun, but its horns itch when sunlight hits them.", "dark", "humanoid", 115, 80, 1400, 3, "https://static.wikia.nocookie.net/palworld/images/0/00/Loupmoon_menu.png/");
		Card galeclaw = new Card(47, "Galeclaw", "A Pal that can easily take flight even while grasping a human.  It is, however, prone to letting go when tired, which has led to the sudden demise of more than a few souls.", "neutral", "bird", 102, 75, 1010, 2, "https://static.wikia.nocookie.net/palworld/images/0/08/Galeclaw_menu.png/");
		Card robinquill = new Card(48, "Robinquill", "A pal that is very similar to humans who hunt and live in the forests. It may prove to be a key for understanding what Pals are and how they diverged from humans so long ago.", "grass", "humanoid", 102, 90, 1050, 5, "https://static.wikia.nocookie.net/palworld/images/b/bb/Robinquill_menu.png/");
		Card gorirat = new Card(49, "Gorirat", "It beats the ground rhythmically to communicate with its comrades. The meaning of each rhythm differs by troop, but the distinction between them is still largely unknown.", "neutral", "humanoid", 102, 90, 1010, 5, "https://static.wikia.nocookie.net/palworld/images/b/b5/Gorirat_menu.png/");
		Card beegarde = new Card(50, "Beegarde", "A servant that pledges loyalty to Elizabee. Any that cause harm to the queen are immediately expelled from the hive. It will gladly give its life to protect its queen.", "grass", "humanoid", 95, 80, 880, 4, "https://static.wikia.nocookie.net/palworld/images/7/7b/Beegarde_menu.png/");
		Card elizabee = new Card(51, "Elizabee", "A chosen queen to rule over Beegardes. There is a never ending stream of servants willing to work themselves to death for the pleasure of serving their queen.", "grass", "humanoid", 102, 90, 5830, 8, "https://static.wikia.nocookie.net/palworld/images/a/a0/Elizabee_menu.png/");
		Card grintale = new Card(52, "Grintale", "Grintale's eyes light up the moment anyone enters its territory. This is no figure of speech-its eyes literally light up.", "neutral", "fourlegged", 90, 110, 4510, 6, "https://static.wikia.nocookie.net/palworld/images/c/c3/Grintale_menu.png/");
		Card swee = new Card(53, "Swee", "Crawling along the ground, it eats microscopic organic matter. After a while, it discharges any substances that provide no nutrition. By using it as a mop for cleaning, everyone wins!", "ice", "other", 80, 60, 180, 1, "https://static.wikia.nocookie.net/palworld/images/b/b5/Swee_menu.png/");
		Card sweepa = new Card(54, "Sweepa", "While hibernating, a large number of Swee hide within its voluminous body hair. The most ever recorded is 101.", "ice", "other", 95, 100, 5400, 6, "https://static.wikia.nocookie.net/palworld/images/f/f3/Sweepa_menu.png/");
		Card chillet = new Card(55, "Chillet", "It can curl up its body and roll around at extremely high speeds. Long ago, people would tie bags of milk to domesticated Chillet as they grazed to produce butter using this spinning force.", "ice", "fourlegged", 90, 90, 2450, 4, "https://static.wikia.nocookie.net/palworld/images/4/49/Chillet_menu.png/");
		Card univolt = new Card(56, "Univolt", "It used to be considered an emissary of the Thunder God, and thus was not hunted by people. However, after witnesses osberved one die from a lightning strike, its reverence faded, and it quite literally fell into the role of a workhorse.", "electric", "fourlegged", 107, 80, 3280, 5, "https://static.wikia.nocookie.net/palworld/images/0/0e/Univolt_menu.png/");
		Card foxcicle = new Card(57, "Foxcicle", "On nights when the aurora is visible, it looks up towards the sky and begins to howl a beautiful song. This does, however, leave it vulnerable to attacks from enemies.", "ice", "fourlegged", 97, 90, 2730, 5, "https://static.wikia.nocookie.net/palworld/images/2/21/Foxcicle_menu.png/");
		Card pyrin = new Card(58, "Pyrin", "It's entire body has evolved into a highly efficient radiator, gifting it with astounding stamina. When someone has mounted it, this Pal takes caution not to burn them.", "fire", "fourlegged", 102, 100, 5720, 6, "https://static.wikia.nocookie.net/palworld/images/e/e6/Pyrin_menu.png/");
		Card reindrix = new Card(59, "Reindrix", "Its transparent cerulean antlers glow with the cold of absolute zero. Any who touch them with their bare hands are instantly frozen over and smashed into pieces.", "ice", "fourlegged", 82, 100, 1800, 4, "https://static.wikia.nocookie.net/palworld/images/c/c1/Reindrix_menu.png/");
		Card rayhound = new Card(60, "Rayhound", "At full speed, it could be mistaken for a bolt of lightning. If two Rayhounds collide, the sound is like that of a powerful thunderclap.", "electric", "fourlegged", 100, 90, 2880, 5, "https://static.wikia.nocookie.net/palworld/images/3/3f/Rayhound_menu.png/");
		Card kitsun = new Card(61, "Kitsun", "Despite its appearance, Kitsun is extremely sensitive and will flee into a cave when spooked. Long ago, it was considered and ill omen if one were found nearby.", "fire", "fourlegged", 92, 100, 2170, 6, "https://static.wikia.nocookie.net/palworld/images/6/6b/Kitsun_menu.png/");
		Card dazzi = new Card(62, "Dazzi", "Often kind to lonely pals. However, the moment a Pal mistakes this for actual companionship, it seizes the opportunity to blast them with a thunderbolt.", "electric", "humanoid", 95, 70, 390, 2, "https://static.wikia.nocookie.net/palworld/images/b/b0/Dazzi_menu.png/");
		Card lunaris = new Card(63, "Lunaris", "It can control those who carelessly stare into its eyes. Those seen with a Lunaris are in its mind, simply under its control.", "neutral", "humanoid", 90, 90, 760, 6, "https://static.wikia.nocookie.net/palworld/images/3/38/Lunaris_menu.png/");
		Card dinossom = new Card(64, "Dinossom", "A Pal who once angered cannot be pacified. It rages on and on like an inferno. The prahse \"step on a Dinossom's tail\" has come to mean enraging someone.", "grass", "humanoid", 87, 110, 2240, 6, "https://static.wikia.nocookie.net/palworld/images/b/b7/Dinossom_menu.png/");
		Card surfent = new Card(65, "Surfent", "Its hydrodynamic form is well suited to life in water. Poachers often catch them and use them in place of surfboards.", "water", "fish", 80, 90, 4050, 4, "https://static.wikia.nocookie.net/palworld/images/1/1d/Surfent_menu.png/");
		Card maraith = new Card(66, "Maraith", "It relishes the peculiar scent living things give off when they are near death. If a Mariath has taken a liking to you. It is safe to assume that is why.", "dark", "fourlegged", 77, 75, 570, 6, "https://static.wikia.nocookie.net/palworld/images/3/32/Maraith_menu.png/");
		Card digtoise = new Card(67, "Digtoise", "A walking contradiction, possessing the strongest shell and the only drill capable of piercing it. \"Digtoise's Fable\" is a popular children's tale.", "ground", "fourlegged", 87, 80, 1980, 5, "https://static.wikia.nocookie.net/palworld/images/5/5b/Digtoise_menu.png/");
		Card tombat = new Card(68, "Tombat", "Often appears out of the blue to flaunt its prized wings in front of other Pals. Although it seems to be an intimidation tactic, the Pal seems to derive some kind of pleasure from the display.", "dark", "humanoid", 97, 95, 2810, 5, "https://static.wikia.nocookie.net/palworld/images/f/f2/Tombat_menu.png/");
		Card lovander = new Card(69, "Lovander", "Seeking a night of love, it is always chasing someone around. At first, it only showed interest in other Pals, but in recent years even humans have become the target of its debauchery.", "neutral", "humanoid", 70, 120, 1450, 5, "https://static.wikia.nocookie.net/palworld/images/c/c8/Lovander_menu.png/");
		Card flambelle = new Card(70, "Flambelle", "When it starts crying, this Pal produces magma in place of tears. The magma that pours out is absorbed back into its body, causing it to get hotter and hotter. The more it cries, the stronger it becomes.", "fire", "humanoid", 85, 60, 1500, 1, "https://static.wikia.nocookie.net/palworld/images/2/20/Flambelle_menu.png/");
		Card vanwyrm = new Card(71, "Vanwyrm", "The melodies of a flute made from the exoskeleton of a Vanwyrm are said to cross the whole mountain ranges. In ages past, such flutes were used to signal an attack.", "fire", "bird", 107, 90, 3360, 4, "https://static.wikia.nocookie.net/palworld/images/e/ea/Vanwyrm_menu.png/");
		Card bushi = new Card(72, "Bushi", "Its body becomes a blade upon death, to be taken up by the next generation. If someone other than a Bushi wields this blade, the soul within torments them until they are driven mad.", "fire", "humanoid", 112, 80, 3520, 7, "https://static.wikia.nocookie.net/palworld/images/7/73/Bushi_menu.png/");
		Card beakon = new Card(73, "Beakon", "Some think it is a related species to Ragnahawk, but there is in fact no connection. Using its sharp beak, it descends on its prey in a quick motion that resembles a bolt of lightning.", "electric", "bird", 107, 105, 6490, 6, "https://static.wikia.nocookie.net/palworld/images/a/a0/Beakon_menu.png/");
		Card ragnahawk = new Card(74, "Ragnahawk", "Some think it is a related species to Beakon, but there is in fact no connection. It mainly eats rocks, and after many long years its beak and head have hardened to accommodate this diet.", "fire", "bird", 102, 95, 5720, 7, "https://static.wikia.nocookie.net/palworld/images/d/dd/Ragnahawk_menu.png/");
		Card katress = new Card(75, "Katress", "With the power of shadows it produces arcane phenomena. It prefers to eat food raw and is particularly hostile towards Wixen", "dark", "humanoid", 102, 90, 3120, 6, "https://static.wikia.nocookie.net/palworld/images/9/9e/Katress_menu.png/");
		Card wixen = new Card(76, "Wixen", "With the power of light, it produces arcane phenomena. It prefers to eat food well-done and is particularly hostile towards Katress.", "fire", "humanoid", 80, 90, 540, 6, "https://static.wikia.nocookie.net/palworld/images/8/85/Wixen_menu.png/");
		Card verdash = new Card(77, "Verdash", "Land that Verdash has run across becomes extremely fertile, with thick vegetation growing there soon after. It will not run anywhere that herbicide has been used.", "grass", "humanoid", 107, 90, 1200, 8, "https://static.wikia.nocookie.net/palworld/images/4/43/Verdash_menu.png/");
		Card vaelet = new Card(78, "Vaelet", "The castle was filled with the king's favorite flowers. A great battle ensued, and flames approached the castle. Amidst the chaos, the spirit of a flower appeared. - From the fairy tale, The King's Flower.", "grass", "humanoid", 100, 100, 960, 8, "https://static.wikia.nocookie.net/palworld/images/2/24/Vaelet_menu.png/");
		Card sibelyx = new Card(79, "Sibelyx", "A Pal that likes the rain,and will often bask in rain showers until the weather clears up. On rainy days, Foxparks can often be found taking shelter beneath it.", "ice", "humanoid", 90, 110, 4900, 7, "https://static.wikia.nocookie.net/palworld/images/6/66/Sibelyx_menu.png/");
		Card elphidran = new Card(80, "Elphidran", "It possesses a demeanor as pure as its appearance suggests. Perhaps because of this, it is sometimes unable to discern good from evil, often allowing wrongdoers to take advantage of it.", "dragon", "humanoid", 80, 110, 4230, 7, "https://static.wikia.nocookie.net/palworld/images/a/a6/Elphidran_menu.png/");
		Card kelpsea = new Card(81, "Kelpsea", "Its personality changes depending on the quality of the water it was born into. Kelpsea born into polluted waters are generally ill-tempered and quickly become delinquents.", "water", "dragon", 85, 70, 260, 1, "https://static.wikia.nocookie.net/palworld/images/1/1b/Kelpsea_menu.png/");
		Card azurobe = new Card(82, "Azurobe", "This Pal's white ribbon turns black if doused with impure water. Given its usefulness in detecting poison, this Pal was once overhunted. This past has left them bitter towards humanity.", "water", "fish", 85, 110, 4600, 7, "https://static.wikia.nocookie.net/palworld/images/a/a0/Azurobe_menu.png/");
		Card cryolinx = new Card(83, "Cryolinx", "It can easily climb steep mountains with its hard claws. However, its short legs make it difficult to descend, often leaving it stranded in high places.", "ice", "humanoid", 120, 100, 7440, 7, "https://static.wikia.nocookie.net/palworld/images/9/9d/Cryolinx_menu.png/");
		Card blazehowl = new Card(84, "Blazehowl", "While it prefers raw meat, it always ends up eating well-done meat. This is due to its blistering claws, which it uses as its weaponâ€”it simply doesn't realize its prey gets burned to a crisp.", "fire", "fourlegged", 105, 105, 3040, 7, "https://static.wikia.nocookie.net/palworld/images/3/33/Blazehowl_menu.png/");
		Card relaxaurus = new Card(85, "Relaxaurus", "Contrary to its blasÃ© appearance, it's quite ferocious. It perceives everything in its sight as prey and will stop at nothing to devour it.", "dragon", "monster", 105, 110, 9240, 8, "https://static.wikia.nocookie.net/palworld/images/0/01/Relaxaurus_menu.png/");
		Card broncherry = new Card(86, "Broncherry", "Its scent drastically changes before and after pairing. It exudes a pleasing aroma after finding a partner, which is called the \"fragrance of first love.\"", "grass", "fourlegged", 85, 120, 1920, 7, "https://static.wikia.nocookie.net/palworld/images/b/bd/Broncherry_menu.png/");
		Card petallia = new Card(87, "Petallia", "A pal that transforms into a massive plant when at the end of its life. Once every ten years, a beautiful flower blooms and a new Petallia is born.", "grass", "humanoid", 97, 100, 2590, 8, "https://static.wikia.nocookie.net/palworld/images/2/28/Petallia_menu.png/");
		Card reptyro = new Card(88, "Reptyro", "Magma-like blood runs throughout its body. If a large amount of water is thrown on it, this water rapidly heats, causing an immense vapor explosion.", "fire", "fourlegged", 102, 110, 5940, 6, "https://static.wikia.nocookie.net/palworld/images/d/d0/Reptyro_menu.png/");
		Card kingpaca = new Card(89, "Kingpaca", "Melpaca serve this Pal. Contests between Kingpaca offer up their vassals as a wager. Those seen alone are losers of such contests.", "neutral", "fourlegged", 92, 120, 4800, 8, "https://static.wikia.nocookie.net/palworld/images/9/9d/Kingpaca_menu.png/");
		Card mammorest = new Card(90, "Mammorest", "The vegetation on its back varies between individuals. There is a long history of appreciating this veritable garden of a Pal, and there are even Mammorest pruning specialists.", "grass", "fourlegged", 92, 150, 8450, 8, "https://static.wikia.nocookie.net/palworld/images/5/5e/Mammorest_menu.png/");
		Card wumpo = new Card(91, "Wumpo", "Researchers once tried to shave off its hair to reveal its true form. In the end, only hair was left, as if that was all there was to begin with.", "ice", "humanoid", 90, 140, 4900, 7, "https://static.wikia.nocookie.net/palworld/images/0/0e/Wumpo_menu.png/");
		Card warsect = new Card(92, "Warsect", "The ultra-hard armor surrounding its body is extremely strong and heat resistant. Even a napalm blast would hardly leave a scratch.", "grass", "humanoid", 100, 120, 5830, 8, "https://static.wikia.nocookie.net/palworld/images/a/a7/Warsect_menu.png/");
		Card fenglope = new Card(93, "Fenglope", "In ancient times, it was a familiar subject for painting because of its beautiful and majestic appearance. Fenglope is an endangered species, the Fenglope whose beautiful fur and horns are much sought after by poachers!", "neutral", "fourlegged", 110, 110, 1250, 3, "https://static.wikia.nocookie.net/palworld/images/6/68/Fenglope_menu.png/");
		Card felbat = new Card(94, "Felbat", "Attacking from the shadows, this Pal traps its prey within its cloak-like wings. It's probably best not to know what happens within them, or why the inside of its wings are stained red.", "dark", "humanoid", 102, 100, 1100, 6, "https://static.wikia.nocookie.net/palworld/images/7/7d/Felbat_menu.png/");
		Card quivern = new Card(95, "Quivern", "Sleeping while cuddling a Quivern is said to be a heavenly experience, but there are some who have been crushed and sent to heaven by ones that toss and turn in their sleep.", "dragon", "dragon", 100, 105, 5830, 7, "https://static.wikia.nocookie.net/palworld/images/d/d9/Quivern_menu.png/");
		Card blazamut = new Card(96, "Blazamut", "Legends say it was born during a volcanic eruption. A strange group even claims that this continent is laid upon the back of a giant Blazamut.", "fire", "fourlegged", 137, 100, 9520, 9, "https://static.wikia.nocookie.net/palworld/images/e/ee/Blazamut_menu.png/");
		Card helzephyr = new Card(97, "Helzephyr", "It calls forth lightning from the depths of hell. One who dies from Helzephyr's inferno is sure to be sent to the underworld.", "dark", "bird", 112, 100, 6840, 7, "https://static.wikia.nocookie.net/palworld/images/3/3c/Helzephyr_menu.png/");
		Card astegon = new Card(98, "Astegon", "A savage beast born of the abyss. Thou shall not stand before the beast. Thou shall not heed the beast.", "dragon", "monster", 112, 100, 7200, 9, "https://static.wikia.nocookie.net/palworld/images/d/d4/Astegon_menu.png/");
		Card menasting = new Card(99, "Menasting", "Being made of pure energy, its insides are completely hollow. This Pal crams still-living prey into its hollow body, where it absorbs them. Hellish screams of pain can often be heard coming from inside this Pal.", "dark", "other", 100, 100, 6050, 9, "https://static.wikia.nocookie.net/palworld/images/5/57/Menasting_menu.png/");
		Card anubis = new Card(100, "Anubis", "Once seen as a symbol of nobility, and an idol for those who shunned wealth and power. Yet over time, this Pal became a token of death.", "ground", "humanoid", 130, 120, 3960, 10, "https://static.wikia.nocookie.net/palworld/images/2/21/Anubis_menu.png/");
		Card jormuntide = new Card(101, "Jormuntide", "Legends says the Jormuntide was once a wise man, who after being wrongly convicted and cast into a whirlpool, returned as this Pal to destroy those who wronged him.", "dragon", "fish", 135, 130, 8320, 8, "https://static.wikia.nocookie.net/palworld/images/8/8e/Jormuntide_menu.png/");
		Card suzaku = new Card(102, "Suzaku", "It was once believed to usher in the dry season. Whenever there was a drought in the previous year, people would relentlessly seek to cull it's numbers, hoping to bring a plentiful harvest in the next year.", "fire", "bird", 102, 120, 8840, 8, "https://static.wikia.nocookie.net/palworld/images/b/b4/Suzaku_menu.png/");
		Card grizzbolt = new Card(103, "Grizzbolt", "With a friendly smile and a hardy physique, it is docile towards one it recognizes as a partner. For reasons unexplained, its personality undergoes a drastic change when wielding a minigun.", "electric", "humanoid", 110, 105, 6720, 8, "https://static.wikia.nocookie.net/palworld/images/1/13/Grizzbolt_menu.png/");
		Card lyleen = new Card(104, "Lyleen", "A docile Pal full of love. It watches over small Pals who have lost their parents. It uses a full-power Solar Blast to discipline naughty Pals.", "grass", "humanoid", 105, 110, 6160, 9, "https://static.wikia.nocookie.net/palworld/images/5/5e/Lyleen_menu.png/");
		Card faleris = new Card(105, "Faleris", "When it finds its prey it unleashes a whirlwind of flames, burning the entire area to ash. Faleris breath is known for its pleasing scent.", "fire", "bird", 102, 100, 5720, 9, "https://static.wikia.nocookie.net/palworld/images/9/99/Faleris_menu.png/");
		Card orserk = new Card(106, "Orserk", "It sends electricity into its foes' wounds, roasting them from the inside out. Fights between Orserk end in the blink of an eye.", "dragon", "humanoid", 115, 100, 7320, 9, "https://static.wikia.nocookie.net/palworld/images/6/6e/Orserk_menu.png/");
		Card shadowbeak = new Card(107, "Shadowbeak", "Forbidden existence born of madness. As he lost his genetic relationship with the other Pals, he may no longer be considered one of them.", "dark", "fourlegged", 125, 120, 8060, 10, "https://static.wikia.nocookie.net/palworld/images/0/0c/Shadowbeak_menu.png/");
		Card paladius = new Card(108, "Paladius", "In the past, he and Necromus were a single species. They say that they are an existence that has freed themselves from all negative feelings, but the depths of their eyes harbor traces of resentment.", "neutral", "fourlegged", 115, 130, 7810, 20, "https://static.wikia.nocookie.net/palworld/images/0/09/Paladius_menu.png/");
		Card necromus = new Card(109, "Necromus", "Once he and Paladius were a single species. They say it is the manifestation of negative feelings, but the depths of their eyes contain traces of compassion.", "dark", "fourlegged", 122, 130, 7930, 20, "https://static.wikia.nocookie.net/palworld/images/1/13/Necromus_menu.png/");
		Card frostallion = new Card(110, "Frostallion", "Guardian deity of Palpagos Island, known as the Winter Caller. In the past, when a calamity struck the land, it soared into the sky and sealed away the threat by casting the island into an eternal winter.", "ice", "fourlegged", 120, 140, 7440, 20, "https://static.wikia.nocookie.net/palworld/images/0/00/Frostallion_menu.png/");
		Card jetragon = new Card(111, "Jetragon", "Looks over the island of Palpagos from the ends of the sky. When the calamity awakens again, splitting the earth and setting the heavens on fire, he will destroy it with a glare of complete obliteration.", "dragon", "dragon", 120, 110, 7680, 20, "https://static.wikia.nocookie.net/palworld/images/e/e5/Jetragon_menu.png/");
		Card jolthog_cryst = new Card(112, "Jolthog Cryst", "It releases cold air stored in its body when under attack. The frigid blast it radiates is cold enough to freeze the surrounding air and easily pierces through any attacker's body.", "ice", "fourlegged", 72, 70, 70, 2, "https://static.wikia.nocookie.net/palworld/images/7/72/Jolthog_Cryst_menu.png");
		Card mau_cryst = new Card(113, "Mau Cryst", "Its crystalline tail is beautiful, but shatters when this Pal dies. Some believe it is good luck to raise one, so Mau Cryst in captivity are treated with great care.", "ice", "fourlegged", 67, 70, 10, 2, "https://static.wikia.nocookie.net/palworld/images/7/7a/Mau_Cryst_menu.png");
		Card gobfin_ignis = new Card(114, "Gobfin Ignis", "Once upon a time, it was a giant and powerful aquatic Pal. However, with the dwindling availability of food, it ventured onto land. As a consequence of burning many calories to walk, it astonishingly awakened its power to control fire!", "fire", "humanoid", 90, 90, 800, 3, "https://static.wikia.nocookie.net/palworld/images/9/9c/Gobfin_Ignis_menu.png");
		Card hangyu_cryst = new Card(115, "Hangyu Cryst", "Its gigantic arms can tear through blocks of ice. There were times when great sinners were tied in the town square and had their hair torn out by as a brutal form of public humiliation.", "ice", "other", 75, 80, 20, 2, "https://static.wikia.nocookie.net/palworld/images/4/49/Hangyu_Cryst_menu.png");
		Card mossanda_lux = new Card(116, "Mossanda Lux", "A Pal whose power is truly shocking. By altering the electrical currents in its body, this Pal's been able to overload its own strength. When it comes to sheer power, this Pal may be top of the list.", "electric", "humanoid", 100, 100, 5610, 7, "https://static.wikia.nocookie.net/palworld/images/0/05/Mossanda_Lux_menu.png");
		Card eikthyrdeer_terra = new Card(117, "Eikthyrdeer Terra", "The individual with the hardest horns becomes the leader. Once the horns are lost, so too is the leadership status. It leaves the herd admist farewell glances and quietly returns to the earth.", "ground", "fourlegged", 75, 95, 1680, 6, "https://static.wikia.nocookie.net/palworld/images/3/32/Eikthyrdeer_Terra_menu.png");
		Card incineram_noct = new Card(118, "Incineram Noct", "It specifically targets baby pals, taking them back to its territory. One can only imagine the profound despair of the parent Pal, whose child has been taken away.", "dark", "humanoid", 127, 95, 3870, 5, "https://static.wikia.nocookie.net/palworld/images/5/5b/Incineram_Noct_menu.png");
		Card leezpunk_ignis = new Card(119, "Leezpunk Ignis", "A Pal that has an unusual obsession with their standing posture. Always in search of the hottest pose, this Pal's owner is constantly presented with fervent stances.", "fire", "humanoid", 85, 80, 640, 3, "https://static.wikia.nocookie.net/palworld/images/e/ea/Leezpunk_Ignis_menu.png");
		Card robinquill_terra = new Card(120, "Robinquill Terra", "A Pal that lives a hunting life in rocky areas and is very close to humans. When bones are found in ruins, there are always human bones found nearby as well.", "grass", "humanoid", 102, 90, 1150, 6, "https://static.wikia.nocookie.net/palworld/images/4/45/Robinquill_Terra_menu.png");
		Card pyrin_noct = new Card(121, "Pyrin Noct", "It burns mysterious dark matter as energy and expels the remaining particles from its body. If someone rides it, they should take care so as not to gallop down the path of darkness.", "fire", "fourlegged", 102, 100, 6270, 7, "https://static.wikia.nocookie.net/palworld/images/2/2b/Pyrin_Noct_menu.png");
		Card dinossom_lux = new Card(122, "Dinossom Lux", "Though struck by lightning, it lives on. The phrase \"struck by a Dinossom Lux's bolt\" has come to mean narrowly escaping death.", "electric", "humanoid", 90, 110, 2380, 7, "https://static.wikia.nocookie.net/palworld/images/c/c7/Dinossom_Lux_menu.png");
		Card surfent_terra = new Card(123, "Surfent Terra", "Its aerodynamic form is well suited to life on the sand. Poachers often catch them and use them in place of surfboards", "ground", "fish", 80, 90, 4140, 5, "https://static.wikia.nocookie.net/palworld/images/f/ff/Surfent_Terra_menu.png");
		Card vanwyrm_cryst = new Card(124, "Vanwyrm Cryst", "The Melodies of a flute made from the exoskeleton of a Vanwyrm Cryst are said to cross whole mountain ranges. In ages past, such flutes were used to signal victory in a battle.", "ice", "bird", 110, 90, 3610, 5, "https://static.wikia.nocookie.net/palworld/images/1/19/Vanwyrm_Cryst_menu.png");
		Card elphidran_aqua = new Card(125, "Elphidran Aqua", "It possesses a demeanor as pure as its appearance suggests. Perhaps because of this, it harbors no ill will in any of its actions and is indifferent even after killing someone.", "dragon", "humanoid", 80, 115, 4320, 8, "https://static.wikia.nocookie.net/palworld/images/5/5e/Elphidran_Aqua_menu.png");
		Card kelpsea_ignis = new Card(126, "Kelpsea Ignis", "Their personalities change depending on the temperature of the water where they were born. Kelpsea born in warm waters generally have a passionate, motivated personality.", "fire", "dragon", 85, 70, 240, 2, "https://static.wikia.nocookie.net/palworld/images/b/ba/Kelpsea_Ignis_menu.png");
		Card blazehowl_noct = new Card(127, "Blazehowl Noct", "While it prefers raw meat, it always ends up eating tainted meat. This is due to its dark claws, which it uses as its weaponâ€”it simply doesn't realize its prey got cursed.", "fire", "fourlegged", 107, 105, 3360, 8, "https://static.wikia.nocookie.net/palworld/images/5/5d/Blazehowl_Noct_menu.png");
		Card relaxaurus_lux = new Card(128, "Relaxaurus Lux", "One day, Relaxaurus had an idea. Maybe it was about time for a change. Just then, an electric shock raced through its body!", "dragon", "monster", 110, 110, 9380, 9, "https://static.wikia.nocookie.net/palworld/images/4/40/Relaxaurus_Lux_menu.png");
		Card broncherry_aqua = new Card(129, "Broncherry Aqua", "Its scent drastically changes before and after pairing. It exudes a pleasing aroma before finding a partner, which is called the \"perfume of purity.\"", "grass", "fourlegged", 87, 120, 2110, 8, "https://static.wikia.nocookie.net/palworld/images/d/db/Broncherry_Aqua_menu.png");
		Card reptyro_cryst = new Card(130, "Reptyro Cryst", "Ice cold blood runs throughout its body. If heated rapidly, its blood evaporates, causing an immense vapor explosion.", "ice", "fourlegged", 102, 110, 6380, 7, "https://static.wikia.nocookie.net/palworld/images/0/09/Reptyro_Cryst_menu.png");
		Card kingpaca_cryst = new Card(131, "Kingpaca Cryst", "With a heart of ice, this Pal is terrible at expressing its emotions. A solitary individual is pitiable, seen as too clumsy in the eyes of Melpaca.", "ice", "fourlegged", 92, 120, 5100, 9, "https://static.wikia.nocookie.net/palworld/images/4/49/Kingpaca_Cryst_menu.png");
		Card mammorest_cryst = new Card(132, "Mammorest Cryst", "The vegetation on its back varies from individual to individual. There was a time when seeds of presumed extinct plants were found still frozen on the back of a Mammorest Cryst.", "ice", "fourlegged", 92, 150, 8580, 9, "https://static.wikia.nocookie.net/palworld/images/d/db/Mammorest_Cryst_menu.png");
		Card wumpo_botan = new Card(133, "Wumpo Botan", "researchers once tried to cut the grass off its body to reveal its true form. In the end, only grass was left, as if that was all there was to begin with.", "grass", "humanoid", 90, 140, 4700, 8, "https://static.wikia.nocookie.net/palworld/images/6/68/Wumpo_Botan_menu.png");
		Card jormuntide_ignis = new Card(134, "Jormuntide Ignis", "Legend says the Jormuntide Ignis was once a warrior who, after being wrongly convicted and cast into a volcano, returned as this Pal to destroy those who wronged him.", "dragon", "fish", 140, 130, 8500, 9, "https://static.wikia.nocookie.net/palworld/images/0/0d/Jormuntide_Ignis_menu.png");
		Card suzaku_aqua = new Card(135, "Suzaku Aqua", "It was once believed to usher in the rainy season. If there was a flood the previous year, people would relentlessly seek to cull its numbers, hoping to avert disaster in the coming year.", "water", "bird", 102, 125, 9110, 9, "https://static.wikia.nocookie.net/palworld/images/a/a1/Suzaku_Aqua_menu.png");
		Card lyleen_noct = new Card(136, "Lyleen Noct", "An elegant Pal full of grace. It admonishes any who are disrespectful with a painful slap. Some Pals actively seek out this punishment.", "dark", "humanoid", 105, 110, 6610, 10, "https://static.wikia.nocookie.net/palworld/images/3/30/Lyleen_Noct_menu.png");
		Card frostallion_noct = new Card(137, "Frostallion Noct", "Guardian deity of Palpagos Island known as the Night Caller. In the past, when a calamity struck the land, it soared into the sky and sealed away the threat by casting the island into eternal darkness.", "dark", "fourlegged", 120, 140, 7560, 20, "https://static.wikia.nocookie.net/palworld/images/1/14/Frostallion_Noct_menu.png");
		cardRepository.save(lamball);
		cardRepository.save(cattiva);
		cardRepository.save(chikipi);
		cardRepository.save(lifmunk);
		cardRepository.save(foxparks);
		cardRepository.save(fuack);
		cardRepository.save(sparkit);
		cardRepository.save(tanzee);
		cardRepository.save(rooby);
		cardRepository.save(pengullet);
		cardRepository.save(penking);
		cardRepository.save(jolthog);
		cardRepository.save(gumoss);
		cardRepository.save(vixy);
		cardRepository.save(hoocrates);
		cardRepository.save(teafant);
		cardRepository.save(depresso);
		cardRepository.save(cremis);
		cardRepository.save(daedream);
		cardRepository.save(rushoar);
		cardRepository.save(nox);
		cardRepository.save(fuddler);
		cardRepository.save(killamari);
		cardRepository.save(mau);
		cardRepository.save(celaray);
		cardRepository.save(direhowl);
		cardRepository.save(tocotoco);
		cardRepository.save(flopie);
		cardRepository.save(mozzarina);
		cardRepository.save(bristla);
		cardRepository.save(gobfin);
		cardRepository.save(hangyu);
		cardRepository.save(mossanda);
		cardRepository.save(woolipop);
		cardRepository.save(caprity);
		cardRepository.save(melpaca);
		cardRepository.save(eikthyrdeer);
		cardRepository.save(nitewing);
		cardRepository.save(ribbuny);
		cardRepository.save(incineram);
		cardRepository.save(cinnamoth);
		cardRepository.save(arsox);
		cardRepository.save(dumud);
		cardRepository.save(cawgnito);
		cardRepository.save(leezpunk);
		cardRepository.save(loupmoon);
		cardRepository.save(galeclaw);
		cardRepository.save(robinquill);
		cardRepository.save(gorirat);
		cardRepository.save(beegarde);
		cardRepository.save(elizabee);
		cardRepository.save(grintale);
		cardRepository.save(swee);
		cardRepository.save(sweepa);
		cardRepository.save(chillet);
		cardRepository.save(univolt);
		cardRepository.save(foxcicle);
		cardRepository.save(pyrin);
		cardRepository.save(reindrix);
		cardRepository.save(rayhound);
		cardRepository.save(kitsun);
		cardRepository.save(dazzi);
		cardRepository.save(lunaris);
		cardRepository.save(dinossom);
		cardRepository.save(surfent);
		cardRepository.save(maraith);
		cardRepository.save(digtoise);
		cardRepository.save(tombat);
		cardRepository.save(lovander);
		cardRepository.save(flambelle);
		cardRepository.save(vanwyrm);
		cardRepository.save(bushi);
		cardRepository.save(beakon);
		cardRepository.save(ragnahawk);
		cardRepository.save(katress);
		cardRepository.save(wixen);
		cardRepository.save(verdash);
		cardRepository.save(vaelet);
		cardRepository.save(sibelyx);
		cardRepository.save(elphidran);
		cardRepository.save(kelpsea);
		cardRepository.save(azurobe);
		cardRepository.save(cryolinx);
		cardRepository.save(blazehowl);
		cardRepository.save(relaxaurus);
		cardRepository.save(broncherry);
		cardRepository.save(petallia);
		cardRepository.save(reptyro);
		cardRepository.save(kingpaca);
		cardRepository.save(mammorest);
		cardRepository.save(wumpo);
		cardRepository.save(warsect);
		cardRepository.save(fenglope);
		cardRepository.save(felbat);
		cardRepository.save(quivern);
		cardRepository.save(blazamut);
		cardRepository.save(helzephyr);
		cardRepository.save(astegon);
		cardRepository.save(menasting);
		cardRepository.save(anubis);
		cardRepository.save(jormuntide);
		cardRepository.save(suzaku);
		cardRepository.save(grizzbolt);
		cardRepository.save(lyleen);
		cardRepository.save(faleris);
		cardRepository.save(orserk);
		cardRepository.save(shadowbeak);
		cardRepository.save(paladius);
		cardRepository.save(necromus);
		cardRepository.save(frostallion);
		cardRepository.save(jetragon);
		cardRepository.save(jolthog_cryst);
		cardRepository.save(mau_cryst);
		cardRepository.save(gobfin_ignis);
		cardRepository.save(hangyu_cryst);
		cardRepository.save(mossanda_lux);
		cardRepository.save(eikthyrdeer_terra);
		cardRepository.save(incineram_noct);
		cardRepository.save(leezpunk_ignis);
		cardRepository.save(robinquill_terra);
		cardRepository.save(pyrin_noct);
		cardRepository.save(dinossom_lux);
		cardRepository.save(surfent_terra);
		cardRepository.save(vanwyrm_cryst);
		cardRepository.save(elphidran_aqua);
		cardRepository.save(kelpsea_ignis);
		cardRepository.save(blazehowl_noct);
		cardRepository.save(relaxaurus_lux);
		cardRepository.save(broncherry_aqua);
		cardRepository.save(reptyro_cryst);
		cardRepository.save(kingpaca_cryst);
		cardRepository.save(mammorest_cryst);
		cardRepository.save(wumpo_botan);
		cardRepository.save(jormuntide_ignis);
		cardRepository.save(suzaku_aqua);
		cardRepository.save(lyleen_noct);
		cardRepository.save(frostallion_noct);

	}

}
